[project]
name = "xpdfpghljk"
version = "0.1.0"

[project.scripts]
cython_test = "xpdfpghljk.hello:hello_world"

[build-system]
build-backend = 'setuptools.build_meta'
requires = ["setuptools", "cython"]
